#Basic settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

#Splitting windows
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

#vim navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

#Reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

#Window management
set -g base-index 1
set -g pane-base-index 1 
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n S-Right next-window
bind -n S-Left previous-window

#Vim style copying
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

#Status Bar Themeing
#Colors
dotbar_bg="#141415"
dotbar_fg="#606079"
dotbar_fg_curr="#cdcdcd"
dotbar_fg_sess="#565B66"
dotbar_fg_pref="#aeaed1"
dotbar_accent="#bb9dbd"

#Basic Settings
set -g status-position "bottom"
set -g status-justify "absolute-centre"
set -g status-style "bg=$dotbar_bg,fg=$dotbar_fg"
set -g status-interval 1
set -g allow-rename on
set -g automatic-rename on

#Script to get repo name or folder name
set -g window-status-separator " • "
dotbar_script="$HOME/.config/tmux/get_window_name.sh"

#Inactive Windows
set -g window-status-format "#[fg=${dotbar_fg},bg=${dotbar_bg}] #($dotbar_script \"#{pane_current_path}\" name \"#{pane_current_command}\") "

#Active Windows
set -g window-status-current-format "#[fg=${dotbar_fg_curr},bg=${dotbar_bg},bold] #($dotbar_script \"#{pane_current_path}\" name \"#{pane_current_command}\") #{?window_zoomed_flag,#[fg=${dotbar_accent}]󰊓 ,}"

#Left&Right Status
set -g status-left-length 100
set -g status-left "#[bg=$dotbar_bg,fg=$dotbar_fg_sess]#{?client_prefix,#[bg=$dotbar_fg_pref]#[fg=$dotbar_bg]#[bold],} #S #[bg=$dotbar_bg,fg=$dotbar_fg_sess,nobold]"

#Logic: Show branch, and if git status is NOT empty, append the checkmark icon
set -g status-right-length 150
set -g status-right "#[fg=$dotbar_fg_pref,bg=$dotbar_bg,bold]#($HOME/.config/tmux/get_window_name.sh #{pane_current_path} git)#[fg=$dotbar_fg_sess,bg=$dotbar_bg,nobold] %H:%M "

#Alerts
set -g window-status-bell-style "bg=$dotbar_fg_pref,fg=$dotbar_bg,bold"
set -g window-status-activity-style "bg=$dotbar_fg_curr,fg=$dotbar_bg"

